import generator
api_key = "....."  # NIEMALS echte Keys einchecken!
model = generator.DEFAULT_MODELS[generator.PROVIDER_GROQ]
gen = generator.QuizGenerator(api_key,generator.PROVIDER_GROQ, model=model)
models = gen.client.models.list()
for m in models.data:
    print(m.id)
txt = "Die Frostluft hat uns nun auch in den östlichen Regionen Deutschlands verlassen und es ist überall milder geworden. Der Schnee taut, oft herrschen Trübeverhältnisse, in manchen Regionen erwarten uns aber auch ein paar Lichtblicke. Die Ausläufe eines Tiefdrucksystems, das vom Atlantik bis nach Mitteleuropa reicht, bringen uns in weiten Landesteilen viele Wolken, milde Luft und immer wieder neues Nass von oben. Einige Regionen Süddeutschlands profitieren allerdings von einem Hoch über den Mittelmeerraum mit den größten Chancen auf etwas Sonne. Am Wochenende kommt dann aus Osten wieder kältere Luft zu uns. Wir schauen uns jetzt an, wie sich die Temperaturen jeweils im Nordosten und Südwesten des Landes entwickeln werden. In Neubrandenburg erwarten wir noch Höchstwerte von 4 oder 5 Grad, doch die Temperaturen gehen ab dem Wochenende zurück und landen bis Mitte der kommenden Woche bei rund 0 Grad. Nachts tritt dann leichter Frost auf. In Karlsruhe ist es dagegen deutlich milder mit 11 bis 13 Grad, bevor auch hier die Temperaturen zurückgehen und sich bei etwa 4 bis 5 Grad einpendeln. Es bestehen zwar noch Unsicherheiten, richtig frostig, wie zuletzt wird es aber wohl erst mal nicht und in trockener Luft ist die Sonne sogar öfter zu sehen. Und nun zum aktuellen Wetter. Der Himmel ist oft Wolken verhangen, zum Teil halten sich auch Nebelfelder. Von Nordwesten her breitet sich Regen oder Nieselregen in die Mitte und den Osten aus, dahinter kommt von der Nordsee her die Sonne zum Vorschein. Im Süden des Landes bleibt es trocken und besonders südlich der Donau sind sonnige Momente dabei. In der Nacht ist es vor allem im Südosten aufgelockert, sonst meist stark bewölkt oder neblig mit wenigen Lücken. Zunächst fällt in den mittleren Landesteilen gegenmorgen auch nach Westen hin gebietsweise Regen. Der Wind weht heute schwachbissmäßig aus südwestlicher im Norden und Nordwesten aus westlicher Richtung. In den Mittelgebirgen ist er auch frisch unterwegs mit stürmischen Böen oder Sturmböen in den Gipfellagen. Heute werden Höchstwerte von 1 Grad bei Dauernebel in Niederbayern bis 13 Grad im Breisgau erreicht. Vom Südwesten bis in die Mitte bleibt die Nacht frostfrei mit 8 bis 2 Grad im Norden, an den Alpen und in Niederbayern herrscht leichter Frost bis minus 4 Grad. Morgen bleibt es oft stark bewölkt oder neblig trüb und immer wieder kann leichter Regen oder Nieselregen fallen. Im Südwesten und Süden ist die Sonne im Tagesverlauf öfter zu sehen. Dazu werden 1 Grad im Bayerischen Wald bis 14 Grad am Oberrhein erreicht. Der Freitag bringt dem Westen etwas Regen, sonst neben Wolken oder Nebel auch sonnige Phasen. Am Samstag wird es aus Osten kälter und die Sonne ist nur gebietsweise zu sehen. Ja, nach Schnee, Frost, Glätte und Sturm ist es also ruhiger geworden beim Wetter und das wird es auch erst mal bleiben."
q=gen.validate_answer("wieviel Kugeln Eis gitb es für 1€?",  "2", "1")
print(q)